path: "data/welddb.csv"
target_col: "yield"
all_targets:
    - "yield"
    - "hardness"
    - "elongation"
    - "reduc_area"
    - "ult_tens_str"
cleaned_data_path: "output/data/welddb.csv"
task: "regression"
#Add hyperparameters configuration